# Generated by Django 5.0.6 on 2024-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_financialitem_month_financialitem_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialitem",
            name="tag",
            field=models.CharField(default="Misc", max_length=50),
        ),
        migrations.AlterField(
            model_name="financialitem",
            name="month",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="financialitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="financialitem",
            name="year",
            field=models.IntegerField(),
        ),
    ]
