# Generated by Django 5.0.6 on 2024-06-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_financialitem_tag_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialitem",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
