# Generated by Django 5.0.6 on 2024-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_financialitem_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialitem",
            name="current_lives",
            field=models.IntegerField(default=3),
        ),
    ]
