# Generated by Django 5.0.6 on 2024-06-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_financialitem_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="progress_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="progress_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
